languageCode: en-us
#baseURL: "//gemin-shrestha.github.io/Gemin-Portfolio/"
baseURL: "https://geminshrestha.com.np/"
title: Gemin Shrestha
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Gemin Shrestha
  description: "I'm Gemin Shrestha. Cyber Security Enthusiast"
  keywords: [Blog, Portfolio, Cyber Security]
  author: Gemin Shrestha
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "March 8, 2024"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Gemin Shrestha"
    icon: "images/coding.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hey! \U0001F44B"
    subtitle: "I'm **Gemin Shrestha** Cyber Security Enthusiast"
    imageUrl: "images/dp.png"
    imageWidth: 180
    imageHeight: 180
    imageTitle: "Gemin Photo"
    buttons:
      - name: Blogs
        #url: blogs
        url: "https://codinggeeks.hashnode.dev/"
      - name: Projects
        #url: projects

  # home-info mode
  homeInfoParams:
    Title: "Hey! \U0001F44B"
    Content: "I'm **Gemin Shrestha** Cyber Security Enthusiast" 

  socialIcons:
    - name: hashnode
      url: "https://codinggeeks.hashnode.dev/"

    - name: linkedin
      url: "https://www.linkedin.com/in/geminshrestha/"
    - name: github
      url: "https://github.com/dataprofessor"


 # analytics:
  #  google:
   #   SiteVerificationTag: "XYZabc"
    #bing:
     # SiteVerificationTag: "XYZabc"
    #yandex:
     # SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: blog
      name: Blogs
      url: "https://codinggeeks.hashnode.dev/"
      #url: /blogs/
      weight: 1
    - identifier: projects
      name: Projects
      #url: /projects/
      weight: 2
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30